events/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns= [
    url(r'^forum/$', views.forum , name='forum'),
     url(r'^events/$', views.events , name='events'),
    url(r'^register/$', views.UserFormView.as_view() , name='register'),
    url(r'^login/$', views.login_user , name='login'),
     url(r'^logout/$', views.logout_user , name='logout'),
    url(r'^$', views.index , name='index'),
    url(r'^about/$', views.about , name='about'),
]

magzine/urls.py
from django.conf.urls import url
from . import views
app_name = 'magzine'
urlpatterns= [
    url(r'^$', views.index, name='index'),
]

members/urls.py
from django.conf.urls import url
from . import views

app_name = 'members'
urlpatterns= [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

events/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.core.urlresolvers  import reverse

class Events(models.Model):
       event_title =models.CharField(max_length=100)
       event_desc =models.CharField(max_length=1000)
       event_image =models.FileField()
       def __str__(self):
           return self.event_title



class Eve_pics(models.Model):
        event= models.ForeignKey (Events, on_delete=models.CASCADE)
        eve_pics = models.FileField()
        eve_date = models.CharField(max_length=100)
        def __str__(self):
           return self.eve_date

magzine/models.py
from django.db import models



class Mags(models.Model):
       magzine_name =models.CharField(max_length=100)
       magzine_year =models.CharField(max_length=10)
       magzine_coverpage = models.FileField()
       def __str__(self):
           return self.magzine_name + '-' + self.magzine_year  

class Cont(models.Model):
       member = models.ForeignKey(Mags , on_delete= models.CASCADE)
       page_title = models.CharField(max_length=100)
       pages= models.FileField()
       def __str__(self):
           return self.page_title

members/models.py
from django.db import models
from django.core.urlresolvers  import reverse

class People(models.Model):
       member_name =models.CharField(max_length=100)
       member_post =models.CharField(max_length=50)
       member_image =models.FileField()
       def __str__(self):
           return self.member_post + '-' + self.member_name       
class Bio(models.Model):
       member = models.ForeignKey (People, on_delete=models.CASCADE)
       desc= models.CharField(max_length=500)
       g_link = models.CharField(max_length=50)
       ln_link = models.CharField(max_length=50)

events/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("hello you are in Events Page ")

home/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import authenticate , login , logout
from . form import UserForm
from django.views import generic
from django.views.generic import View
from .models import Events , Eve_pics





def index(request):
    if not request.user.is_authenticated():
        return render(request, 'home/login.html')
    else :
       upcoming = Events.objects.all()
       return render(request, 'home/index.html', {'upcoming' : upcoming })

def events(request):
 event = Events.objects.get(pk=1);
 return render(request, 'home/events.html', {'event' : event})

def about(request):
 return render(request, 'home/about.html', {})



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'home/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                upcoming = Events.objects.all()
                userinfo= request.user
                return render(request, 'home/index.html', {'upcoming' : upcoming,'userinfo': userinfo})
            else:
                return render(request, 'home/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'home/login.html', {'error_message': 'Invalid login'})
    return render(request, 'home/login.html')

class UserFormView(View):
    form_class= UserForm
    template_name= 'home/registration_form.html'
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form': form})
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
             user = form.save(commit=False)
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             user.set_password(password)
             user.save()
             user = authenticate(username=username, password=password)
             if user is not None:
               if user.is_active:
                 login(request, user)

                 return render(request, 'home/index.html', )
        context = {
        "form": form,
              }
        return render(request, 'home/registration_form.html', context)

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'home/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'home/registration_form.html', context)

def forum(request):
    if not request.user.is_authenticated():
        return render(request, 'home/login.html')
    else:
      return render(request, 'home/forum.html', {})

magzine/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template  import loader
from django.shortcuts import get_object_or_404, render
from . models import Mags, Cont

def index(request):
      all_magzines = Mags.objects.all()
      context={ 'all_magzines' :all_magzines }
      return render(request, 'magzine/index.html', context)

members/views.py
from django.http import HttpResponse
from django.template  import loader
from django.shortcuts import get_object_or_404, render
from .models import People, Bio



def index(request):
      all_members = People.objects.all()
      context={ 'all_members' :all_members }
      return render(request, 'members/index.html', context)



def detail(request, id):
        member= get_object_or_404(People, kwargs = id)
        return render(request, 'members/detail.html' , {'member' : member})

home/templates/home/about.html
{% extends 'members/base.html' %}
{% block title %}About {% endblock %}
{% block body %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style1.css' %}" />
<div class="container-fluid">
<div class="jumbotron"> About</div>
<div class="row">
<div class="col-md-4 col-sm-12 col-md-offset-2"><p>dsgesfhrtjnytgdjmtygdm</p>
<img src="" /></div>
<div class="col-md-6 col-sm-12"><p>fgnjfgjmgydkmgth,mdfhfdgs</p></div>

</div>
</div>






{% endblock %}

home/templates/home/base_visitor.html
<!DOCTYPE html>
<head>
<title>{% block title %}
{% endblock %}
</title>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a href="{% url 'home:index' %}" class="navbar-brand">ChEA &nbsp;| IIChE </a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</div>
<div class="collapse navbar-collapse" id="mynavbar">
<ul class="nav navbar-nav">
<li><a href="{% url 'home:index' %}">HOME</a> </li>
<li><a href="{% url 'members:index' %}">MEMBERS</a> </li>
<li><a href="#">GUEST LECTURES</a> </li>
</ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home:register' %}" ><span class="glyphicon glyphicon-user"> </span>&nbsp;REGISTER</a></li>
		<li><a href="{% url 'home:login' %}" ><span class="glyphicon glyphicon-log-in"> </span>&nbsp;LOGIN</a></li>

	</ul>
</div>
</div>

</nav>
{% block body %}
{% endblock %}
<footer>
<br><br><br>

<hr>
<h6 style="color:blue; text-align: center;"> please like us on</h6>
<div class="footer" style="text-align:center;">

<a href="https://www.facebook.com/ChEANITW/" style="text-align: center;"><i class="fa fa-facebook fa-center fa-2x" area-hidden="true"> </i></a>&nbsp;
<a href="#" ><i class="fa fa-linkedin fa-center fa-2x" area-hidden="true"> </i></a>&nbsp;
<a href="#" ><i class="fa fa-envelope fa-center fa-2x" area-hidden="true"> </i></a>&nbsp;
<a href="#"><i class="fa fa-twitter fa-center fa-2x" area-hidden="true"> </i></a>
</div>
</footer>
</body>

</html>

home/templates/home/events.html
{% extends 'members/base.html' %}
<span class="glyphicon glyphicon-picture">{% block title %}Events{% endblock %}</span>
{% block register_active %}active{% endblock %}

{% block body %}
{% if event %}
<style>
#border:hover{

}
#image:hover{
 border: 2px solid #777;
filter:blur(1px) ;
transition: all 0.2s ease-in-out;}
</style>
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<!-- ISO section -->
				<div class="iso-section">
						<h3 style="text-align:center;">{{event.event_title}}</h3><hr>
			              <p style="color:black; font-weight:thin ;text-align:center;">
							  Department orientation is organised in second week of august to make freshers aware of available
							  </br>opportunities and introducing them to profesors and the council</p>
					 <div class="iso-box-section wow fadeIn" data-wow-delay="0.9s">
               			<div class="iso-box-wrapper col4-iso-box" style="padding-left:0px;" >
                              {% for eve in event.eve_pics_set.all %}
               				 <div class="iso-box ori  col-lg-4 col-md-4 col-sm-6" style="padding-left:0px;" id="border">
               				 	<a href="{{eve.eve_pics.url}}" style="padding-left:0px;" data-lightbox-gallery="portfolio-gallery">
									<img src="{{eve.eve_pics.url}}"  width="420" height="320"  alt="portfolio img" id="image" style="padding-left:0px;">&nbsp;</a>
               				 </div>{% endfor  %}
						</div>
					 </div>
				</div>
			</div>
		</div>


{% else %}
<h3> you have no pics </h3>
{% endif %}

{% endblock %}

home/templates/home/experiance.html
{% extends 'members/base.html' %}
{% block title %}experiance {% endblock %}
{% block body %}

home/templates/home/forum.html
{% extends 'members/base.html' %}
{% block title %}Enquiry{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

	<div class="container">
		<div class="row">
             <div class="col-md-3" > </div>
			<div class="col-md-6 col-sm-12">
				<h1 style="margin-top:20px; text-align:center; color:teal;">Enquiry</h1>
				<br><br>
				<form style="" action="{% url 'home:forum' %}" method="post" class="wow fadeInUp form-group" data-wow-delay="0.6s">
					     {% csrf_token %}

							<input type="text"  placeholder="Name" name="name"  class="form-control"><br>


						<input type="email" class="form-control" placeholder="Email" name="email"><br>


						<textarea class="form-control" placeholder="Message" rows="7" name="message" style="height:200px; width:100%;"></textarea>

<br>
					<button class="btn btn-primary btn-block " type="submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;SEND US</button>


				</form>
		       </div>
			</div>
	      </div>
{% endblock %}

home/templates/home/guest_lectures.html
{% extends 'members/base.html' %}
{% block title%}home {% endblock %}
{% block body%}
{% load staticfiles %}
<div class="container">
<







</div>

home/templates/home/index.html
{% extends 'members/base.html' %}
{% block title%}home {% endblock %} 
{% block body%}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />

{% if upcoming %}




  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      {% for event in upcoming %}
          {% if forloop.first %}
             <div class="item active">
          {% else %}
               <div class="item">
          {% endif %}
        <img src="{{ event.event_image.url }}" alt="{{ event.event_title.url }}" style="width:100%;">
                  <div class="carousel-caption">
           <section id="home">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h3>NIT Warangal</h3>
				<h1>Chemical Engineering Association</h1>
				<hr>
                       <h2 style="text-align:center;padding-top:40px; color:teal;">UPCOMING EVENTS</h2><br><br>
                        <div class="col-md-12 col-sm-12">
				<a href="{% url 'home:events' %}" class="smoothScroll btn btn-danger" style="font-family: Calibri Light;">&nbsp;EVENTS  &nbsp;</a>
				<a href="{% url 'magzine:index' %}" class="smoothScroll btn btn-default" style="font-family: Calibri Light;">&nbsp;MAGZINES&nbsp;&nbsp; </a>
			</div><br/>
                    <div class="col-md-12 col-sm-12">
				<a href="{% url 'home:about' %}" class="smoothScroll btn btn-danger" style="font-family: Calibri Light;">ABOUT US</a>
				<a href="{% url 'members:index' %}" class="smoothScroll btn btn-default" style="font-family: Calibri Light;">CONTACT US</a>
			</div>
                   </div>
		</div>
</section>
        </div>
               </div>
      {% endfor %}

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

{% else %}
<h2 style="text-align: center;">YOU DONT HAVE ANY UPCOMING EVENTS</h2>
{% endif %}
{% endblock %}

home/templates/home/login.html
{% extends 'home/base_visitor.html' %}
{% block title %}Login{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container">

<div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
             {% if error_message %}
       <h2 style="text-align:center;"><strong style="color: red;text-align:center;font-size:20px;">{{ error_message }}</strong></h2>
         {% else %}
             <h2 style="text-align:center; color: Blue;">LOGIN</h2>
             {% endif %}
 <form action="{% url 'home:login' %}" method="POST">
              {% csrf_token %}
  <div class="form-group">
    <label for="email">Username:</label>
    <input type="text" class="form-control" id="email" name="username">
  </div><br>
  <div class="form-group">
    <label for="password">Password:</label>
    <input type="password" class="form-control" id="password" name="password">
  </div><br><br>
  <button type="submit" class="btn btn-primary btn-block">LOGIN</button>
</form><br><br>
            <div class="footer">
                    Don't have an account? <a href="{% url 'home:register' %}">Click here</a> to register.
                </div>
        </div>
</div>
</div>

{% endblock %}

home/templates/home/registration_form.html
{% extends 'home/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container">




    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <h2 style="text-align:center;">Register</h2>
          <form action="{% url 'home:register' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
    <label for="username">Username:</label>
    <input type="text" class="form-control" name="username" id="username">
  </div><br>
  <div class="form-group">
    <label for="email">Email address:</label>
    <input type="email" class="form-control" name="email" id="email">
  </div><br>
  <div class="form-group">
    <label for="password">Password:</label>
    <input type="password" class="form-control" name="password" id="password">
  </div><br>
              <div class="form-group">
    <label for="password">Confirm Password:</label>
    <input type="password" class="form-control" name="conf-password">
  </div><br>
  <div class="form-group">
    <label for="mobile">Mobile No:</label>
    <input type="text" class="form-control" name="mobile" id="mobile">
  </div><br><br>
  <button type="submit" class="btn btn-primary btn-block">Submit</button>
</form><br><br>
             <div class="footer">
                    Already have an account? <a href="{% url 'home:login' %}">Click here</a> to log in.
                </div>

</div>
</div>
</div>
<br><br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

magzine/templates/magzine/index.html
{% extends 'members/base.html' %} 
{% block title%}magzines {% endblock %} 
{% block body %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'magzine/style.css' %}" />
    <div class="jumbotron" > Our Magzines 
                                                                       </div>
{% for mags in all_magzines %}
<div class="row" id="mags">
<div class="col-lg-5 col-sm-12"><div class="gallery">
<a target="_balnk" href="#">
                 <img src="{{mags.magzine_coverpage.url }}"  alt="turbulenz" class="img-responsive" /> </a>
                 <div class="desc"> <b> {{mags.magzine_name }} </b></div>
</div> </div>
<div class="col-lg-1"></div>
<div class="col-lg-5 col-sm-12"> 
<div class="gallery">
<a target="_balnk" href="#">
                 <img src="{{mags.magzine_coverpage.url }}"  alt="turbulenz" class="img-responsive" /> </a>
                 <div class="desc">  {{mags.magzine_name }} </div>
</div>
</div>
</div>
{% endfor  %}
{% endblock %}

members/templates/members/base.html
<!DOCTYPE html>
<head>
<title>{% block title %}
{% endblock %}
</title>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a href="#" class="navbar-brand">ChEA &nbsp;| IIChE </a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</div>
<div class="collapse navbar-collapse" id="mynavbar">
<ul class="nav navbar-nav">
<li><a href="{% url 'home:index' %}">HOME</a> </li>
<li><a href="{% url 'members:index' %}">MEMBERS</a> </li>
<li><a href="#">GUEST LECTURES</a> </li>
</ul>
	<ul class="nav navbar-nav navbar-right">

		<li><a href="{% url 'home:forum' %}">{{userinfo.username}}</a> </li>
		<li><a href="{% url 'home:forum' %}">FORUMS</a> </li>
		<li><a href="{% url 'home:logout' %}"><span class="glyphicon glyphicon-off"> </span>&nbsp;Logout</a> </li>

	</ul>
</div>
</div>

</nav>
{% block body %}
{% endblock %}
<footer>
<br><br><br>

<hr>
<h6 style="color:blue; text-align: center;"> please like us on</h6>
<div class="footer" style="text-align:center;">

<a href="https://www.facebook.com/ChEANITW/" style="text-align: center;"><i class="fa fa-facebook fa-center fa-2x" area-hidden="true"> </i></a>&nbsp;
<a href="#" ><i class="fa fa-linkedin fa-center fa-2x" area-hidden="true"> </i></a>&nbsp;
<a href="#" ><i class="fa fa-envelope fa-center fa-2x" area-hidden="true"> </i></a>&nbsp;
<a href="#"><i class="fa fa-twitter fa-center fa-2x" area-hidden="true"> </i></a>
</div>
</footer>
</body>

</html>

members/templates/members/detail.html
{% extends 'members/base.html' %}

{% block body %}


{% endblock %}

members/templates/members/index.html
{% extends 'members/base.html' %}
{% block title%}members{% endblock %} 
{% block body %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'members/style.css' %}" />
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<div class="jumbotron">
    <div class="row"><b>Our Team </b>
    </div>
</div>
{% if all_members %}
{% for member in all_members %}
   <div class="row" >
	   {% if forloop.first %}
			<div class="col-md-6 col-sm-12 col-md-offset-4" style="padding-left:20px;" >
				<div class="team-member">
					<img src="{{member.member_image.url}}" class="img-responsive img-circle" alt="{{member.member_image.url}}" id="imgs">
					<h4>{{member.member_name}}</h4>
					<p class="text-muted">{{member.member_post}}</p>
					<p class="text-muted"></p>
					<ul class="list-inline social-buttons">
						<li><a href="#"><i class="fa fa-envelope"></i></a></li>
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
	   {% else %}
			<div class="col-md-6 col-sm-12 col-md-offset-4" style="padding-left:20px;" >
				<div class="team-member">
					<img src="{{member.member_image.url}}" class="img-responsive img-circle" alt="{{member.member_image.url}}" id="imgs">
					<h4>{{member.member_name}}</h4>
					<p class="text-muted">{{member.member_post}}</p>
					<p class="text-muted"></p>
					<ul class="list-inline social-buttons">
						<li><a href="#"><i class="fa fa-envelope"></i></a></li>
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
	   {% endif %}
  </div>

{% endfor %}
{% else %}
<h2> you don't have any records </h2>
{% endif %}
<br/><br/>
{% endblock %}